// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistoryEntry(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddHistoryEntry'](arg1, arg2, arg3, arg4);
}

export function CheckHealth() {
  return window['go']['main']['App']['CheckHealth']();
}

export function GetBaseURL() {
  return window['go']['main']['App']['GetBaseURL']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetHistoryCount() {
  return window['go']['main']['App']['GetHistoryCount']();
}

export function GetHistoryEntry(arg1) {
  return window['go']['main']['App']['GetHistoryEntry'](arg1);
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetPatterns() {
  return window['go']['main']['App']['GetPatterns']();
}

export function IsServerRunning() {
  return window['go']['main']['App']['IsServerRunning']();
}

export function LoadPreferences() {
  return window['go']['main']['App']['LoadPreferences']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function SendChat(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendChat'](arg1, arg2, arg3, arg4);
}

export function SetBaseURL(arg1) {
  return window['go']['main']['App']['SetBaseURL'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
