// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddHistoryEntry(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CheckHealth():Promise<boolean>;

export function GetBaseURL():Promise<string>;

export function GetHistory():Promise<Array<main.HistoryEntry>>;

export function GetHistoryCount():Promise<number>;

export function GetHistoryEntry(arg1:number):Promise<main.HistoryEntry>;

export function GetModels():Promise<main.ModelsResponse>;

export function GetPatterns():Promise<Array<string>>;

export function IsServerRunning():Promise<boolean>;

export function LoadPreferences():Promise<main.Preferences>;

export function OpenFileDialog():Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SavePreferences(arg1:main.Preferences):Promise<void>;

export function SendChat(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetBaseURL(arg1:string):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;
